
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 17 04:05:08 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 45;
  public static final int CONST = 21;
  public static final int CASE = 24;
  public static final int NOTEQUAL = 28;
  public static final int LPAREN = 6;
  public static final int GREATER = 27;
  public static final int SEMI = 5;
  public static final int CONTINUE = 33;
  public static final int LESS = 25;
  public static final int MINUS = 18;
  public static final int RPAREN = 7;
  public static final int AND = 22;
  public static final int OR = 35;
  public static final int BOOL = 42;
  public static final int COMMA = 8;
  public static final int CLASS = 31;
  public static final int INC = 20;
  public static final int DIV = 17;
  public static final int PLUS = 11;
  public static final int IF = 46;
  public static final int LESSEQ = 32;
  public static final int LSQBRACE = 34;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int ISEQUAL = 41;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int NUMBER = 43;
  public static final int MOD = 38;
  public static final int IDENT = 44;
  public static final int BREAK = 40;
  public static final int VOID = 13;
  public static final int SWITCH = 23;
  public static final int COLON = 14;
  public static final int ELSE = 47;
  public static final int LBRACE = 3;
  public static final int READ = 26;
  public static final int WHILE = 29;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int GREATEREQ = 37;
  public static final int RSQBRACE = 36;
  public static final int DEC = 19;
  public static final int PRINT = 9;
  public static final int DO = 30;
}

